// This file is automatically generated by smiggins/langs/_generator.py.
// DO NOT EDIT THIS FILE DIRECTLY. All changes WILL be overwritten.

type languages = "en" | "en_GB" | "es";
type LanguageData = {
  meta: { id: languages, name: string, fallbacks: languages[], maintainers: [string | null, string][], past_maintainers: [string | null, string][] },
  "notifications": {"followed": string, "folreq": string, "comment": string, "quote": string, "ping": string, "message": {[key in number | "*"]: string}, "no_content_title": string, "no_content_body": string}
};

const LANGS: { [key in languages]: LanguageData } = {
  "en": {"meta": {"id": "en", "name": "English", "fallbacks": [], "maintainers": [["trinkey", "trinkey"]], "past_maintainers": []}, "notifications": {"followed": "%n (@%u) started following you.", "folreq": "%n (@%u) wants to follow you.", "comment": "%n (@%u): %c", "quote": "%n (@%u): %c", "ping": "%n (@%u): %c", "message": {"0": "%n (@u) messaged you", "1": "%n (@u) messaged you and %c other", "*": "%n (@u) messaged you and %c others"}, "no_content_title": "Notification", "no_content_body": "No notification context was given."}},
  "en_GB": {"meta": {"id": "en_GB", "name": "English (United Kingdom)", "fallbacks": ["en"], "maintainers": [["trinkey", "trinkey"]], "past_maintainers": []}, "notifications": {"followed": "%n (@%u) started following you.", "folreq": "%n (@%u) wants to follow you.", "comment": "%n (@%u): %c", "quote": "%n (@%u): %c", "ping": "%n (@%u): %c", "message": {"0": "%n (@u) messaged you", "1": "%n (@u) messaged you and %c other", "*": "%n (@u) messaged you and %c others"}, "no_content_title": "Notification", "no_content_body": "No notification context was given."}},
  "es": {"meta": {"id": "es", "name": "Español", "fallbacks": ["en"], "maintainers": [["pq-on-tempe2", "pquirrel"]], "past_maintainers": []}, "notifications": {"followed": "%n (@%u) started following you.", "folreq": "%n (@%u) wants to follow you.", "comment": "%n (@%u): %c", "quote": "%n (@%u): %c", "ping": "%n (@%u): %c", "message": {"0": "%n (@u) messaged you", "1": "%n (@u) messaged you and %c other", "*": "%n (@u) messaged you and %c others"}, "no_content_title": "Notification", "no_content_body": "No notification context was given."}},
};

const DEFAULT_LANGUAGE: languages = "en";

let L: LanguageData;

// TODO: localStorage isn't supported on service workers - need to look up solution at some point
// L = LANGS[localStorage.getItem("smiggins-language") as languages | null || DEFAULT_LANGUAGE];
// if (!L) {
//   L = LANGS[DEFAULT_LANGUAGE];
// }
L = LANGS[DEFAULT_LANGUAGE];
