$schema: "http://json-schema.org/draft-07/schema#"
type: object
re:
- &color "^(?:#[a-zA-Z0-9]{6}(?:[a-zA-Z0-9]{2})?|@accent(?:-50)?)$"
- &color_noop "^#[a-zA-Z0-9]{6}$"
- &color_noa "^#[a-zA-Z0-9]{6}(?:[a-zA-Z0-9]{2})?$"
properties:
  version: { type: [string, "null"] }
  site_name: { type: string }
  website_url: { type: string }
  debug: { type: boolean }
  google_verification_tag: { type: [string, "null"] }
  owner_user_id: { type: integer }
  enable_sitemaps: { type: boolean }
  alternate_ips: { type: [boolean, string] }
  items_per_sitemap:
    type: integer
    minimum: 50
    maximum: 50000
  generic_cache_timeout: { type: [integer, "null"] }
  sitemap_cache_timeout: { type: [integer, "null"] }
  favicon_cache_timeout: { type: [integer, "null"] }
  favicon_data: { type: [string, "null"] }
  enable_dynamic_favicon: { type: boolean }
  enable_email: { type: boolean }
  max_admin_log_lines:
    type: integer
    minimum: 1
  default_language: { type: string }
  discord_invite: { type: [string, "null"] }
  default_dark_theme:
    type: string
    anyOf:
      - enum:
        - noon
        - dawn
        - dusk
        - dark
        - sunset
        - midnight
        - black
      - type: string
  default_light_theme:
    type: string
    anyOf:
      - enum:
        - noon
        - dawn
        - dusk
        - dark
        - sunset
        - midnight
        - black
      - type: string
  cache_languages: { type: [boolean, "null"] }
  allow_scraping: { type: boolean }
  allow_indexing: { type: boolean }
  max_username_length:
    type: integer
    minimum: 1
    maximum: 200
  max_display_name_length:
    type: integer
    minimum: 1
    maximum: 200
  max_user_bio_length:
    type: integer
    minimum: 1
    maximum: 65536
  max_content_warning_length:
    type: integer
    minimum: 1
    maximum: 200
  max_post_length:
    type: integer
    minimum: 1
    maximum: 65536
  max_poll_options:
    type: integer
    minimum: 2
  max_poll_option_length:
    type: integer
    minimum: 1
  default_banner_color:
    type: string
    pattern: *color_noop
  posts_per_request:
    type: integer
    minimum: 1
  messages_per_request:
    type: integer
    minimum: 1
  max_notifications:
    type: integer
    minimum: 1
  contact_information:
    type: array
    items:
     type: array
     minItems: 2
     maxItems: 2
     items:
      - type: string
        enum:
        - url
        - email
        - text
      - type: string
  post_webhooks:
    type: object
    patternProperties:
      "[a-zA-Z0-9\\-_]+":
        type: array
        minItems: 2
        maxItems: 2
        items:
          - type: string
          - type: string
            enum:
            - raw
            - discord
    additionalProperties: false
  source_code: { type: boolean }
  ratelimit: { type: boolean }
  api_timings:
    type: object
    properties:
      "signup unsuccessful": { type: integer }
      "signup successful": { type: integer }
      "login unsuccessful": { type: integer }
      "login successful": { type: integer }
      "create comment": { type: integer }
      "create comment failure": { type: integer }
      "create post": { type: integer }
      "create post failure": { type: integer }
    additionalProperties: false
  enable_user_bios: { type: boolean }
  enable_pronouns: { type: boolean }
  enable_gradient_banners: { type: boolean }
  enable_account_switcher: { type: boolean }
  enable_hashtags: { type: boolean }
  enable_private_messages: { type: boolean }
  enable_pinned_posts: { type: boolean }
  enable_post_deletion: { type: boolean }
  enable_editing_posts: { type: boolean }
  enable_contact_page: { type: boolean }
  enable_credits_page: { type: boolean }
  enable_badges: { type: boolean }
  enable_quotes: { type: boolean }
  enable_polls: { type: boolean }
  enable_content_warnings: { type: boolean }
  enable_logged_out_content: { type: boolean }
  enable_new_accounts: { type: boolean }
  custom_themes:
    type: array
    items:
      type: object
      properties:
        name:
          type: object
          properties:
            default: { type: string }
          additionalProperties: true
          required: [default]
        id:
          type: string
          not:
            enum:
            - custom
            - auto
            - warm
            - light
            - gray
            - dark
            - black
            - oled
            - dawn
            - dusk
            - midnight
        light_theme: { type: boolean }
        colors:
          type: object
          properties:
            text: { type: string, pattern: *color }
            subtext: { type: string, pattern: *color }
            red: { type: string, pattern: *color }
            background: { type: string, pattern: *color_noop }
            post_background: { type: string, pattern: *color }
            content_warning_background: { type: string, pattern: *color }
            input_background: { type: string, pattern: *color }
            checkbox_background: { type: string, pattern: *color }
            button_background: { type: string, pattern: *color }
            button_hover_background: { type: string, pattern: *color }
            button_inverted_background: { type: string, pattern: *color }
            input_border: { type: string, pattern: *color }
            checkbox_border: { type: string, pattern: *color }
            button_border: { type: string, pattern: *color }
            modal_backdrop: { type: string, pattern: *color }
            modal_background: { type: string, pattern: *color }
            modal_border: { type: string, pattern: *color }
            gray: { type: string, pattern: *color }
            accent:
              type: object
              properties:
                rosewater: { type: string, pattern: *color_noa }
                flamingo: { type: string, pattern: *color_noa }
                pink: { type: string, pattern: *color_noa }
                mauve: { type: string, pattern: *color_noa }
                red: { type: string, pattern: *color_noa }
                maroon: { type: string, pattern: *color_noa }
                peach: { type: string, pattern: *color_noa }
                yellow: { type: string, pattern: *color_noa }
                green: { type: string, pattern: *color_noa }
                teal: { type: string, pattern: *color_noa }
                sky: { type: string, pattern: *color_noa }
                sapphire: { type: string, pattern: *color_noa }
                blue: { type: string, pattern: *color_noa }
                lavender: { type: string, pattern: *color_noa }
              additionalProperties: false
              required: [rosewater, flamingo, pink, mauve, red, maroon, peach, yellow, green, teal, sky, sapphire, blue, lavender]
          additionalProperties: false
          required: [text, subtext, red, background, post_background, content_warning_background, input_background, checkbox_background, button_background, button_hover_background, button_inverted_background, input_border, checkbox_border, button_border, modal_backdrop, modal_background, modal_border, gray, accent]
      additionalProperties: false
      required: [name, id, light_theme, colors]
additionalProperties: false

# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
