# Generated by Django 6.0.6 on 2026-06-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('tag', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='M2MBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M2MFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M2MMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M2MPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.TextField(unique=True)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M2MMessageMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.messagegroup')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='posts.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=65535)),
                ('content_warning', models.TextField(blank=True, max_length=255, null=True)),
                ('timestamp', models.IntegerField()),
                ('scheduled', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
                ('private', models.BooleanField(null=True)),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('quoted_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='posts.post'),
        ),
        migrations.CreateModel(
            name='M2MLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='M2MHashtagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'hashtag')},
            },
        ),
        migrations.AddField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='hashtags', through='posts.M2MHashtagPost', to='posts.post'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.TextField(null=True)),
                ('auth_key', models.CharField(max_length=64, unique=True)),
                ('legacy_token', models.CharField(max_length=64, null=True, unique=True)),
                ('admin_level', models.IntegerField(default=0)),
                ('display_name', models.CharField(max_length=255)),
                ('bio', models.CharField(blank=True, default='', max_length=65535)),
                ('color', models.CharField(max_length=7)),
                ('color_two', models.CharField(blank=True, default='#000000', max_length=7)),
                ('gradient', models.BooleanField(default=False)),
                ('pronouns', models.CharField(blank=True, default='', max_length=255)),
                ('default_post_private', models.BooleanField(default=False)),
                ('verify_followers', models.BooleanField(default=False)),
                ('blocking', models.ManyToManyField(blank=True, related_name='blockers', through='posts.M2MBlock', through_fields=('user', 'blocking'), to='posts.user')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', through='posts.M2MFollow', through_fields=('user', 'following'), to='posts.user')),
                ('muting', models.ManyToManyField(blank=True, related_name='muters', through='posts.M2MMute', through_fields=('user', 'muting'), to='posts.user')),
                ('pending_followers', models.ManyToManyField(blank=True, related_name='pending_following', through='posts.M2MPending', through_fields=('user', 'following'), to='posts.user')),
                ('pinned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('keys', models.TextField()),
                ('expires', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='posts.M2MLike', to='posts.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('event_type', models.CharField(max_length=7)),
                ('linked_follow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.m2mfollow')),
                ('linked_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.m2mlike')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('is_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.user')),
            ],
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='members',
            field=models.ManyToManyField(related_name='message_groups', through='posts.M2MMessageMember', to='posts.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=65535)),
                ('timestamp', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='posts.messagegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='posts.user')),
            ],
        ),
        migrations.AddField(
            model_name='m2mpending',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_follow_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mpending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mmute',
            name='muting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mmute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mmessagemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mfollow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mblock',
            name='blocking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_obj', to='posts.user'),
        ),
        migrations.AddField(
            model_name='m2mblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_obj', to='posts.user'),
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user')),
            ],
            options={
                'unique_together': {('poll', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='m2mpending',
            unique_together={('user', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='m2mmute',
            unique_together={('user', 'muting')},
        ),
        migrations.AlterUniqueTogether(
            name='m2mmessagemember',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='m2mlike',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='m2mfollow',
            unique_together={('user', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='m2mblock',
            unique_together={('user', 'blocking')},
        ),
    ]
