# Generated by Django 5.0.1 on 2024-01-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=65536)),
                ('creator', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('likes', models.JSONField()),
                ('comments', models.JSONField()),
                ('reposts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=65536)),
                ('creator', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('likes', models.JSONField()),
                ('comments', models.JSONField()),
                ('reposts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=300)),
                ('token', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=300)),
                ('theme', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=7)),
                ('private', models.BooleanField()),
                ('following', models.JSONField()),
                ('posts', models.JSONField()),
                ('followers', models.JSONField()),
            ],
        ),
    ]
