# Generated by Django 5.0.2 on 2024-02-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_timestamp_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
