# Generated by Django 5.0.2 on 2024-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reposts',
            field=models.JSONField(blank=True),
        ),
    ]
