# Generated by Django 5.0.2 on 2024-02-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comments_comments_alter_comments_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='reposts',
            field=models.JSONField(blank=True),
        ),
    ]
