# Generated by Django 5.0.2 on 2024-04-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_user_color_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gradient',
            field=models.BooleanField(default=False),
        ),
    ]
