# Generated by Django 5.0.2 on 2024-04-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote_is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
