# Generated by Django 5.0.2 on 2024-04-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_reposts_comment_quotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('svg_data', models.CharField(max_length=65536)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.JSONField(default=list),
        ),
    ]
