# Generated by Django 5.0.2 on 2024-04-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_badge_user_badges_alter_user_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_level',
            field=models.IntegerField(default=0),
        ),
    ]
