# Generated by Django 5.0.2 on 2024-04-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_user_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='color_two',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
