# Generated by Django 5.0.2 on 2024-04-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_user_bio_alter_user_color_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
