# Generated by Django 5.0.2 on 2024-04-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_user_badges_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='quotes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
