# Generated by Django 5.0.2 on 2024-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
