# Generated by Django 5.0.2 on 2024-04-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_comment_parent_is_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
