# Generated by Django 5.0.2 on 2024-04-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.JSONField(default=list),
        ),
    ]
