# Generated by Django 5.0.2 on 2024-05-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_badge_users_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocking',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
