# Generated by Django 5.0.4 on 2024-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_user_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(default='__', max_length=2),
        ),
    ]
