# Generated by Django 5.0.2 on 2024-05-04 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_user_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('event_type', models.CharField(max_length=7)),
                ('event_id', models.IntegerField()),
                ('is_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user')),
            ],
        ),
    ]
