# Generated by Django 5.0.2 on 2024-05-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_alter_comment_comment_id_alter_user_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
