# Generated by Django 5.0.2 on 2024-05-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
