# Generated by Django 5.0.2 on 2024-05-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_badge_users_alter_user_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocking',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='color_two',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
