# Generated by Django 5.0.2 on 2024-05-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_comment_comments_alter_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_notifs',
            field=models.BooleanField(default=True),
        ),
    ]
