# Generated by Django 5.0.4 on 2024-05-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_user_read_notifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinned',
            field=models.IntegerField(default=0),
        ),
    ]
