# Generated by Django 5.0.2 on 2024-05-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_user_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessageContainer',
            fields=[
                ('container_id', models.CharField(max_length=601, primary_key=True, serialize=False, unique=True)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_reference_one', to='posts.user')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_reference_two', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.IntegerField()),
                ('content', models.CharField(max_length=65536)),
                ('from_user_one', models.BooleanField()),
                ('message_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.privatemessagecontainer')),
            ],
        ),
    ]
