# Generated by Django 5.0.4 on 2024-05-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_privatemessagecontainer_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='read_messages',
            field=models.IntegerField(default=0),
        ),
    ]
