# Generated by Django 5.0.2 on 2024-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poll',
            field=models.JSONField(default=None, null=True),
        ),
    ]
