# Generated by Django 5.0.6 on 2024-07-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_post_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_warning',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_warning',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
