# Generated by Django 5.0.6 on 2024-07-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_comment_content_warning_post_content_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
