# Generated by Django 5.0.7 on 2024-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_urlpart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlpart',
            old_name='reason',
            new_name='intent',
        ),
        migrations.AddField(
            model_name='urlpart',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='email_valid',
            field=models.BooleanField(default=False),
        ),
    ]
