# Generated by Django 5.0.7 on 2024-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_private_rewrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_warning',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_warning',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='poll',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
