# Generated by Django 5.0.7 on 2024-08-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_alter_comment_content_alter_comment_content_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_followers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
