# Generated by Django 5.0.7 on 2024-09-25 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_admin_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('uname_for', models.TextField(null=True)),
                ('info', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('u_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_by', to='posts.user')),
                ('u_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_for', to='posts.user')),
            ],
        ),
    ]
