# Generated by Django 5.1.1 on 2024-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_comment_edited_post_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.IntegerField(null=True),
        ),
    ]
