# Generated by Django 5.0.7 on 2024-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_db_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
