# Generated by Django 5.0.7 on 2024-12-08 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_pronoun_rewrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_regex', models.BooleanField(default=False)),
                ('string', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted_words', to='posts.user')),
            ],
        ),
    ]
