# Generated by Django 5.1.4 on 2025-01-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_mutedword_hard_mute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratelimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.IntegerField()),
                ('route_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=64)),
            ],
        ),
    ]
