# Generated by Django 5.1.4 on 2025-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_ratelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='read_notifs',
        ),
        migrations.AddField(
            model_name='privatemessagecontainer',
            name='unread_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessagecontainer',
            name='unread_two',
            field=models.BooleanField(default=False),
        ),
    ]
