# Generated by Django 5.2.5 on 2025-09-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_poll_rewrite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
        # Was erroring when attempting to migrate, commenting seems to fix it?
        # migrations.RemoveField(
        #     model_name='m2mbadgeuser',
        #     name='badge',
        # ),
        migrations.AlterUniqueTogether(
            name='m2mbadgeuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='m2mbadgeuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mutedword',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ratelimit',
        ),
        migrations.RemoveField(
            model_name='urlpart',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userpronouns',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpronouns',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_valid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
        migrations.AlterField(
            model_name='user',
            name='blocking',
            field=models.ManyToManyField(blank=True, related_name='blockers', through='posts.M2MBlock', through_fields=('user', 'blocking'), to='posts.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='posts.M2MFollow', through_fields=('user', 'following'), to='posts.user'),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='M2MBadgeUser',
        ),
        migrations.DeleteModel(
            name='MutedWord',
        ),
        migrations.DeleteModel(
            name='URLPart',
        ),
        migrations.DeleteModel(
            name='UserPronouns',
        ),
    ]
