# Generated by Django 5.2.5 on 2025-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_flatten_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_warning',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='privatemessagecontainer',
            name='container_id',
            field=models.CharField(max_length=511, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
