# Generated by Django 5.2.1 on 2025-09-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0063_alter_hashtag_tag_alter_post_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('event_type', models.CharField(max_length=7)),
                ('is_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.user')),
                ('linked_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.m2mlike')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
