# Generated by Django 5.2.5 on 2025-10-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_recreate_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
