# Generated by Django 6.0.1 on 2026-05-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0070_pushnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_obj', to='posts.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting_obj', to='posts.user')),
            ],
            options={
                'unique_together': {('user', 'muting')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='muting',
            field=models.ManyToManyField(blank=True, related_name='muters', through='posts.M2MMute', through_fields=('user', 'muting'), to='posts.user'),
        ),
    ]
