# Generated by Django 6.0.6 on 2026-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0071_m2mmute_user_muting'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
